# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "hashicorp/bionic64"
  config.vm.box_url = "https://vagrantcloud.com/hashicorp/bionic64"

  command_ip = `ip route | awk '/default/ { print $5 }'`
  config.vm.network "public_network", bridge:  command_ip.strip 

  #can be multiple in order. 
  config.vm.provision :shell, path: "scripts/apt_update_and_keys.sh" , privileged:false
  config.vm.provision :shell, path: "scripts/install_dockerio.sh" , privileged:false
  config.vm.provision :shell, path: "scripts/install_chectl.sh" , privileged:false
  config.vm.provision :shell, path: "scripts/install_kubectl.sh" , privileged:false
  config.vm.provision :shell, path: "scripts/install_minikube.sh" , privileged:false
  config.vm.provision :shell, path: "scripts/install_helm.sh" , privileged:false

  config.trigger.after :up do |trigger|
    trigger.run_remote = {inline: "su vagrant -c\"sudo ip route del default via 10.0.2.2\""}
    trigger.name = "Cluster installed!"
  end

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--cpus", `#{RbConfig::CONFIG['host_os'] =~ /darwin/ ? 'sysctl -n hw.ncpu' : 'nproc'}`.chomp]
    vb.memory = 8192
  end

  config.vm.synced_folder ".", "/cert"

end
